Feature15
The-Cage-s-Farm/theCagesFam pull request #32
Opened 2021-04-09 12:06 UTC by MagnoCarta

2021-04-09 14:55 UTC, beacarlos requested changes

2021-04-09 14:55 UTC, beacarlos commented on CagesFarm/CagesFarm/Extensions/Images.swift
> +    case tonyAstonished,tonyAngry,tonyPensive,tonySmiling,tonyTalkingSprite0,tonyTalkingSprite1,quadro,quartoBackground,quadroPerspectiva,comodaFechada,interruptor,cama,lightSwitchOff,lightSwitchOn,t
Falta espaços e na minha opinião acho que assim fica muito exaustivo, colocaria caso a caso.
case tonyAstonished, tonyAngry, tonyPensive, tonySmiling ,tonyTalkingSprite0, tonyTalkingSprite1, quadro, quartoBackground, quadroPerspectiva, comodaFechada, interruptor, cama, lightSwitchOff, lightSwitchOn, tapeteQuadrado, bau

2021-04-09 14:55 UTC, beacarlos commented on CagesFarm/CagesFarm/Nodes/DialogueBox.swift
Espaço desnecessário

2021-04-09 14:55 UTC, beacarlos commented on CagesFarm/CagesFarm/Nodes/DialogueBox.swift
> +
Espaço desnecessário

2021-04-09 14:55 UTC, beacarlos commented on CagesFarm/CagesFarm/Nodes/InteractableObjects.swift
> +
Espaço desnecessário

2021-04-09 14:55 UTC, beacarlos commented on CagesFarm/CagesFarm/Nodes/InteractableObjects.swift
>      }
Aqui parece pelo review do github que tem uma fechamento } perdido, caso não seja, por favor desconsiderar.

2021-04-09 14:55 UTC, beacarlos commented on CagesFarm/CagesFarm/Nodes/InteractableObjects.swift
> +
função sem escopo.

2021-04-09 14:55 UTC, beacarlos commented on CagesFarm/CagesFarm/Nodes/Inventory.swift
>          //self.addChild(textureBackground)
Codigo comentado

2021-04-11 21:36 UTC, beacarlos commented
O pull request está conflitos que impedem de ser aprovado para merge com a dev.

2021-04-20 11:53 UTC, MagnoCarta commented
Still need test

2021-04-20 12:19 UTC, merged